{
 "title": "sk-1",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "node_exporter1", "query": "172.31.2.169:9100" },
   { "name": "node_exporter2", "query": "172.31.20.83:9100" },
   { "name": "node_exporter3", "query": "172.31.29.133:9100" },
   { "name": "node_exporter4", "query": "172.31.42.206:9100" },
   { "name": "checkoutservice", "query": "6bf88c5496-wdndf" },
   { "name": "currencyservice", "query": "55f95958d5-nmqz6" },
   { "name": "emailservice", "query": "779468c985-4rc2g" },
   { "name": "frontend1", "query": "94bd4bd7-2rcvp" },
   { "name": "frontend2", "query": "94bd4bd7-bhfm6" },
   { "name": "loadgenerator", "query": "c57fbc8bb-q9b47" },
   { "name": "paymentservice", "query": "7d886f68fd-67gs5" },
   { "name": "productcatalogservice", "query": "c98749584-zflfv" },
   { "name": "recommendationservice1", "query": "cf7c44cbf-9b2v7" },
   { "name": "recommendationservice2", "query": "cf7c44cbf-dbpz9" },
   { "name": "rediscartservice", "query": "7cd77c554d-jxhp7" },
   { "name": "shippingservice", "query": "84756bb8fb-f9987" },
   { "name": "cartservice", "query": "7b66865965-jrmlb" },
   { "name": "locust", "query": "172.31.46.219:9646" },
   { "name": "mongodb" },
   { "name": "acmeweb" },
   { "name": "probeapp1" },
   { "name": "probeapp2" }
  ]
 },
 "panels": [
  {
   "title": "All Exp",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter1}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Avg Host Node1 CPU Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter1}\", cpu=\"0\"}[5m]) * 100)",
     "legendFormat": "Host Node1 CPU 0 Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter1}\", cpu=\"1\"}[5m]) * 100)",
     "legendFormat": "Host Node1 CPU 1 Usage"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter2}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Avg Host Node2 CPU Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter2}\", cpu=\"0\"}[5m]) * 100)",
     "legendFormat": "Host Node2 CPU 0 Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter2}\", cpu=\"1\"}[5m]) * 100)",
     "legendFormat": "Host Node2 CPU 1 Usage"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter3}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Avg Host Node3 CPU Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter3}\", cpu=\"0\"}[5m]) * 100)",
     "legendFormat": "Host Node3 CPU 0 Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter3}\", cpu=\"1\"}[5m]) * 100)",
     "legendFormat": "Host Node3 CPU 1 Usage"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter4}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Avg Host Node4 CPU Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter4}\", cpu=\"0\"}[5m]) * 100)",
     "legendFormat": "Host Node4 CPU 0 Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter4}\", cpu=\"1\"}[5m]) * 100)",
     "legendFormat": "Host Node4 CPU 1 Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"cartservice-7964c86448-f5nhr\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"cartservice-7964c86448-f5nhr\"}))*100",
     "legendFormat": "cartservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"checkoutservice-${checkoutservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"checkoutservice-${checkoutservice}\"}))*100",
     "legendFormat": "checkoutservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"currencyservice-${currencyservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"currencyservice-${currencyservice}\"}))*100",
     "legendFormat": "currencyservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"emailservice-${emailservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"emailservice-${emailservice}\"}))*100",
     "legendFormat": "emailservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"frontend-${frontend1}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"frontend-${frontend1}\"}))*100",
     "legendFormat": "frontend 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"frontend-${frontend2}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"frontend-${frontend2}\"}))*100",
     "legendFormat": "frontend 2 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"loadgenerator-${loadgenerator}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"loadgenerator-${loadgenerator}\"}))*100",
     "legendFormat": "loadgenerator CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"paymentservice-${paymentservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"paymentservice-${paymentservice}\"}))*100",
     "legendFormat": "paymentservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"productcatalogservice-${productcatalogservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"productcatalogservice-${productcatalogservice}\"}))*100",
     "legendFormat": "productcatalogservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice1}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice1}\"}))*100",
     "legendFormat": "recommendationservice 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice2}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice2}\"}))*100",
     "legendFormat": "recommendationservice 2 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"redis-cart-${rediscartservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"redis-cart-${rediscartservice}\"}))*100",
     "legendFormat": "redis-cart CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"shippingservice-${shippingservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"shippingservice-${shippingservice}\"}))*100",
     "legendFormat": "shippingservice CPU Usage"
    },
    {
     "expr": "locust_requests_avg_response_time{name=\"Aggregated\"}",
     "legendFormat": "Average Response Time"
    },
    {
     "expr": "locust_requests_median_response_time{name=\"Aggregated\"}",
     "legendFormat": "Median Response Time"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_95",
     "legendFormat": "Current Response Time Percentile 95"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_50",
     "legendFormat": "Current Response Time Percentile 50"
    },
    { "expr": "locust_users", "legendFormat": "Number of Users" },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"${node_exporter1}\"} - node_memory_MemAvailable_bytes{job=\"node_exporter\", instance=\"${node_exporter1}\"}",
     "legendFormat": "Host Node 1 Mem Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"${node_exporter2}\"} - node_memory_MemAvailable_bytes{job=\"node_exporter\", instance=\"${node_exporter2}\"}",
     "legendFormat": "Host Node 2 Mem Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"${node_exporter3}\"} - node_memory_MemAvailable_bytes{job=\"node_exporter\", instance=\"${node_exporter3}\"}",
     "legendFormat": "Host Node 3 Mem Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"${node_exporter4}\"} - node_memory_MemAvailable_bytes{job=\"node_exporter\", instance=\"${node_exporter4}\"}",
     "legendFormat": "Host Node 4 Mem Usage"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"${node_exporter1}\"}",
     "legendFormat": "Host Node 1 Mem Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"${node_exporter3}\"}",
     "legendFormat": "Host Node 3 Mem Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"${node_exporter2}\"}",
     "legendFormat": "Host Node 2 Mem Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"node_exporter\", instance=\"${node_exporter4}\"}",
     "legendFormat": "Host Node 4 Mem Total"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"cartservice-${cartservice}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "cartservice Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"checkoutservice-${checkoutservice}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "checkoutservice Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"currencyservice-${currencyservice}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "currencyservice Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"emailservice-${emailservice}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "emailservice Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"frontend-${frontend1}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "frontend 1 Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"frontend-${frontend2}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "frontend 2 Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"loadgenerator-${loadgenerator}\",container_label_io_kubernetes_container_name=\"main\"}",
     "legendFormat": "loadgenerator Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"paymentservice-${paymentservice}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "paymentservice Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"productcatalogservice-${productcatalogservice}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "productcatalogservice Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice1}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "recommendationservice 1 Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice2}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "recommendationservice 2 Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"redis-cart-${rediscartservice}\",container_label_io_kubernetes_container_name=\"redis\"}",
     "legendFormat": "redis-cart Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"shippingservice-${shippingservice}\",container_label_io_kubernetes_container_name=\"server\"}",
     "legendFormat": "shippingservice Mem Usage"
    },
    {
     "expr": "locust_requests_num_requests{name=\"Aggregated\"}",
     "legendFormat": "locust_requests_num_requests"
    },
    {
     "expr": "locust_requests_current_rps{instance=\"${locust}\",job=\"locust\",method=\"GET\",name=\"/\"}",
     "legendFormat": "current_rps GET /"
    },
    {
     "expr": "locust_requests_current_rps{instance=\"${locust}\",job=\"locust\",method=\"GET\",name=\"/cart\"}",
     "legendFormat": "current_rps GET /cart"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/0PUK6V6EV0\"}",
     "legendFormat": "current_rps GET /product/0PUK6V6EV0"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/1YMWWN1N4O\"}",
     "legendFormat": "current_rps GET /product/1YMWWN1N4O"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/2ZYFJ3GM2N\"}",
     "legendFormat": "current_rps GET /product/2ZYFJ3GM2N"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/66VCHSJNUP\"}",
     "legendFormat": "current_rps GET /product/66VCHSJNUP"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/6E92ZMYYFZ\"}",
     "legendFormat": "current_rps GET /product/6E92ZMYYFZ"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/9SIQT8TOJO\"}",
     "legendFormat": "current_rps GET /product/9SIQT8TOJO"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/L9ECAV7KIM\"}",
     "legendFormat": "current_rps GET /product/L9ECAV7KIM"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/LS4PSXUNUM\"}",
     "legendFormat": "current_rps GET /product/LS4PSXUNUM"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/OLJCESPC7Z\"}",
     "legendFormat": "current_rps GET /product/OLJCESPC7Z"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"POST\",name=\"/cart\"}",
     "legendFormat": "current_rps POST /cart"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"POST\",name=\"/cart/checkout\"}",
     "legendFormat": "current_rps POST /cart/checkout"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"POST\",name=\"/setCurrency\"}",
     "legendFormat": "current_rps POST /setCurrency"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",name=\"Aggregated\"}",
     "legendFormat": "current_rps Aggregated"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"acme-web-${acmeweb}\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"acme-web-${acmeweb}\"}))*100",
     "legendFormat": "Acme-Web CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"mongodb-${mongodb}\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"mongodb-${mongodb}\"}))*100",
     "legendFormat": "MongoDB CPU Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"acme-web-${acmeweb}\",container_label_io_kubernetes_docker_type=\"container\",}",
     "legendFormat": "Acme Web Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"mongodb-${mongodb}\",container_label_io_kubernetes_docker_type=\"container\",}",
     "legendFormat": "MongoDB  Mem Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"probe-app-${probeapp1}\"}[20s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"probe-app-${probeapp1}\"}))*100",
     "legendFormat": "StressNG 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"probe-app-${probeapp2}\"}[20s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"probe-app-${probeapp2}\"}))*100",
     "legendFormat": "StressNG 2 CPU Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"probe-app-${probeapp1}\",container_label_io_kubernetes_docker_type=\"container\",}",
     "legendFormat": "StressNG 1 Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"probe-app-${probeapp2}\",container_label_io_kubernetes_docker_type=\"container\",}",
     "legendFormat": "StressNG 2 Mem Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"mosquitto-9c759c54b-2bvwf\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"mosquitto-9c759c54b-2bvwf\"}))*100",
     "legendFormat": "Mosquitto CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"nodered-55b864bffd-z8xx7\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"nodered-55b864bffd-z8xx7\"}))*100",
     "legendFormat": "NodeRed CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"influxdb-589cddb57b-ffpt6\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"influxdb-589cddb57b-ffpt6\"}))*100",
     "legendFormat": "InfluxDB CPU Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"mosquitto-9c759c54b-2bvwf\"}",
     "legendFormat": "Mosquitto Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"nodered-55b864bffd-z8xx7\"}",
     "legendFormat": "NodeRed Mem Usage"
    },
    {
     "expr": "container_memory_working_set_bytes{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"influxdb-589cddb57b-ffpt6\"}",
     "legendFormat": "InfluxDB Mem Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter1}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Avg Host Node1 CPU Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter1}\", cpu=\"0\"}[5m]) * 100)",
     "legendFormat": "Host Node1 CPU 0 Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter1}\", cpu=\"1\"}[5m]) * 100)",
     "legendFormat": "Host Node1 CPU 1 Usage"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter2}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Avg Host Node2 CPU Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter2}\", cpu=\"0\"}[5m]) * 100)",
     "legendFormat": "Host Node2 CPU 0 Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter2}\", cpu=\"1\"}[5m]) * 100)",
     "legendFormat": "Host Node2 CPU 1 Usage"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter3}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Avg Host Node3 CPU Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter3}\", cpu=\"0\"}[5m]) * 100)",
     "legendFormat": "Host Node3 CPU 0 Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter3}\", cpu=\"1\"}[5m]) * 100)",
     "legendFormat": "Host Node3 CPU 1 Usage"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter4}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "Avg Host Node4 CPU Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter4}\", cpu=\"0\"}[5m]) * 100)",
     "legendFormat": "Host Node4 CPU 0 Usage"
    },
    {
     "expr": "100 - (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\", instance=\"${node_exporter4}\", cpu=\"1\"}[5m]) * 100)",
     "legendFormat": "Host Node4 CPU 1 Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"cartservice-7964c86448-f5nhr\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"cartservice-7964c86448-f5nhr\"}))*100",
     "legendFormat": "cartservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"checkoutservice-${checkoutservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"checkoutservice-${checkoutservice}\"}))*100",
     "legendFormat": "checkoutservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"currencyservice-${currencyservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"currencyservice-${currencyservice}\"}))*100",
     "legendFormat": "currencyservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"emailservice-${emailservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"emailservice-${emailservice}\"}))*100",
     "legendFormat": "emailservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"frontend-${frontend1}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"frontend-${frontend1}\"}))*100",
     "legendFormat": "frontend 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"frontend-${frontend2}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"frontend-${frontend2}\"}))*100",
     "legendFormat": "frontend 2 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"loadgenerator-${loadgenerator}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"loadgenerator-${loadgenerator}\"}))*100",
     "legendFormat": "loadgenerator CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"paymentservice-${paymentservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"paymentservice-${paymentservice}\"}))*100",
     "legendFormat": "paymentservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"productcatalogservice-${productcatalogservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"productcatalogservice-${productcatalogservice}\"}))*100",
     "legendFormat": "productcatalogservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice1}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice1}\"}))*100",
     "legendFormat": "recommendationservice 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice2}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice2}\"}))*100",
     "legendFormat": "recommendationservice 2 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"redis-cart-${rediscartservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"redis-cart-${rediscartservice}\"}))*100",
     "legendFormat": "redis-cart CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"shippingservice-${shippingservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"shippingservice-${shippingservice}\"}))*100",
     "legendFormat": "shippingservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"acme-web-${acmeweb}\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"acme-web-${acmeweb}\"}))*100",
     "legendFormat": "Acme-Web CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"mongodb-${mongodb}\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"mongodb-${mongodb}\"}))*100",
     "legendFormat": "MongoDB CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"probe-app-${probeapp1}\"}[20s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"probe-app-${probeapp1}\"}))*100",
     "legendFormat": "StressNG 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"probe-app-${probeapp2}\"}[20s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"probe-app-${probeapp2}\"}))*100",
     "legendFormat": "StressNG 2 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"mosquitto-9c759c54b-2bvwf\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"mosquitto-9c759c54b-2bvwf\"}))*100",
     "legendFormat": "Mosquitto CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"nodered-55b864bffd-z8xx7\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"nodered-55b864bffd-z8xx7\"}))*100",
     "legendFormat": "NodeRed CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"influxdb-589cddb57b-ffpt6\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"influxdb-589cddb57b-ffpt6\"}))*100",
     "legendFormat": "InfluxDB CPU Usage"
    }
   ]
  },
  {
   "title": "Locust Workload",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "locust_requests_avg_response_time{name=\"Aggregated\"}",
     "legendFormat": "Average Response Time"
    },
    {
     "expr": "locust_requests_median_response_time{name=\"Aggregated\"}",
     "legendFormat": "Median Response Time"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_95",
     "legendFormat": "Current Response Time Percentile 95"
    },
    {
     "expr": "locust_requests_current_response_time_percentile_50",
     "legendFormat": "Current Response Time Percentile 50"
    },
    { "expr": "locust_users", "legendFormat": "Number of Users" },
    {
     "expr": "locust_requests_num_requests{name=\"Aggregated\"}",
     "legendFormat": "locust_requests_num_requests"
    },
    {
     "expr": "locust_requests_current_rps{instance=\"${locust}\",job=\"locust\",method=\"GET\",name=\"/\"}",
     "legendFormat": "current_rps GET /"
    },
    {
     "expr": "locust_requests_current_rps{instance=\"${locust}\",job=\"locust\",method=\"GET\",name=\"/cart\"}",
     "legendFormat": "current_rps GET /cart"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/0PUK6V6EV0\"}",
     "legendFormat": "current_rps GET /product/0PUK6V6EV0"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/1YMWWN1N4O\"}",
     "legendFormat": "current_rps GET /product/1YMWWN1N4O"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/2ZYFJ3GM2N\"}",
     "legendFormat": "current_rps GET /product/2ZYFJ3GM2N"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/66VCHSJNUP\"}",
     "legendFormat": "current_rps GET /product/66VCHSJNUP"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/6E92ZMYYFZ\"}",
     "legendFormat": "current_rps GET /product/6E92ZMYYFZ"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/9SIQT8TOJO\"}",
     "legendFormat": "current_rps GET /product/9SIQT8TOJO"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/L9ECAV7KIM\"}",
     "legendFormat": "current_rps GET /product/L9ECAV7KIM"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/LS4PSXUNUM\"}",
     "legendFormat": "current_rps GET /product/LS4PSXUNUM"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"GET\",name=\"/product/OLJCESPC7Z\"}",
     "legendFormat": "current_rps GET /product/OLJCESPC7Z"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"POST\",name=\"/cart\"}",
     "legendFormat": "current_rps POST /cart"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"POST\",name=\"/cart/checkout\"}",
     "legendFormat": "current_rps POST /cart/checkout"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",method=\"POST\",name=\"/setCurrency\"}",
     "legendFormat": "current_rps POST /setCurrency"
    },
    {
     "expr": "locust_requests_current_rps{job=\"locust\",name=\"Aggregated\"}",
     "legendFormat": "current_rps Aggregated"
    },
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\", instance=\"${node_exporter4}\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "avg nide 4 cpu usage"
    }
   ]
  },
  {
   "title": "Cadvisor-containers",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"cartservice-7964c86448-f5nhr\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"cartservice-7964c86448-f5nhr\"}))*100",
     "legendFormat": "cartservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"checkoutservice-${checkoutservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"checkoutservice-${checkoutservice}\"}))*100",
     "legendFormat": "checkoutservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"currencyservice-${currencyservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"currencyservice-${currencyservice}\"}))*100",
     "legendFormat": "currencyservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"emailservice-${emailservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"emailservice-${emailservice}\"}))*100",
     "legendFormat": "emailservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"frontend-${frontend1}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"frontend-${frontend1}\"}))*100",
     "legendFormat": "frontend 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"frontend-${frontend2}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"frontend-${frontend2}\"}))*100",
     "legendFormat": "frontend 2 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"loadgenerator-${loadgenerator}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"loadgenerator-${loadgenerator}\"}))*100",
     "legendFormat": "loadgenerator CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"paymentservice-${paymentservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"paymentservice-${paymentservice}\"}))*100",
     "legendFormat": "paymentservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"productcatalogservice-${productcatalogservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"productcatalogservice-${productcatalogservice}\"}))*100",
     "legendFormat": "productcatalogservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice1}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice1}\"}))*100",
     "legendFormat": "recommendationservice 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice2}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"recommendationservice-${recommendationservice2}\"}))*100",
     "legendFormat": "recommendationservice 2 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"redis-cart-${rediscartservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"redis-cart-${rediscartservice}\"}))*100",
     "legendFormat": "redis-cart CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"shippingservice-${shippingservice}\"}[2m]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"shippingservice-${shippingservice}\"}))*100",
     "legendFormat": "shippingservice CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"acme-web-${acmeweb}\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"acme-web-${acmeweb}\"}))*100",
     "legendFormat": "Acme-Web CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"mongodb-${mongodb}\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"mongodb-${mongodb}\"}))*100",
     "legendFormat": "MongoDB CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"probe-app-${probeapp1}\"}[20s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"probe-app-${probeapp1}\"}))*100",
     "legendFormat": "StressNG 1 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"probe-app-${probeapp2}\"}[20s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"probe-app-${probeapp2}\"}))*100",
     "legendFormat": "StressNG 2 CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"mosquitto-9c759c54b-2bvwf\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"mosquitto-9c759c54b-2bvwf\"}))*100",
     "legendFormat": "Mosquitto CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"nodered-55b864bffd-z8xx7\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"nodered-55b864bffd-z8xx7\"}))*100",
     "legendFormat": "NodeRed CPU Usage"
    },
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{job=\"cadvisor\",container_label_io_kubernetes_pod_name=\"influxdb-589cddb57b-ffpt6\"}[30s]))/count(container_cpu_load_average_10s{container_label_io_kubernetes_pod_name=\"influxdb-589cddb57b-ffpt6\"}))*100",
     "legendFormat": "InfluxDB CPU Usage"
    }
   ]
  }
 ]
}