global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.13.255:9100', '172.31.20.240:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.14.193:8080', '172.31.30.18:8080']

  - job_name: 'locust'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.31.29.131:9646']